### PR TITLE
Issues with publisher install on centos6

### PR DESCRIPTION
**Pull request by wannesvc**
Hi, I'm very new to chef, so I'm not sure if this is the correct way to fix this.
I had issues with ark failing to extract the archive on centos 6.5 and publisher plugin 4.1.10.
Come to think about it... the /etc/httpd location is different depending on the os.

### CODE REVIEW

**Comment by Psukhe** [comment]
Can you post the error you're getting in your logs?
Thanks!

**Comment by wannesvc** [comment]
Hi! First of all, thanks a bunch for your awesome module. + I think I owe you a partial apology.
The error I get (vagrant + centos 7.1):

           ================================================================================
           Error executing action `cherry_pick` on resource 'ark[dispatcher-apache2.4-linux-x86-64-4.1.10.tar.gz]'
           ================================================================================
           
           ArgumentError
           -------------
           You must supply a name when declaring a directory resource
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/ark/providers/default.rb:227:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/aem/providers/dispatcher.rb
           
            57:         ark filename do
            58:           url dispatcher_uri
            59:           checksum dispatcher_checksum
            60:           creates "modules/dispatcher-#{webserver_type}-*#{dispatcher_version}.so"
            61:           path apache_libexecdir
            62:           action :cherry_pick
            63:         end
            64:       end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/aem/providers/dispatcher.rb:57:in `block in class_from_file'
           
           ark("dispatcher-apache2.4-linux-x86-64-4.1.10.tar.gz") do
             provider LWRP provider ark from cookbook ark
             action [:cherry_pick]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :ark
             cookbook_name "aem"
             url "https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_8/file.res/dispatcher-apache2.4-linux-x86-64-4.1.10.tar.gz"
             creates "modules/dispatcher-apache2.2-*4.1.0.so"
             extension "tar.gz"
             release_file "/tmp/kitchen/cache/dispatcher-apache2.4-linux-x86-64-4.1.10.tar.gz.tar.gz"
           end
           

there are 2 issues:

60:           creates "modules/dispatcher-#{webserver_type}-*#{dispatcher_version}.so"  
----> when I remove the '*', it works on both AWS amazon linux and centos 7.1


And if that is fixed, I have another error on the line:

local_file_path = "#{apache_libexecdir}/#{dispatcher_file_path}" 

On centos, apache_libexecdir is not correctly resolved, but on AWS amazon linux it is. But I guess, it's a problem in the "apache" cookbook and not in the aem one, as the value comes from: node[:apache][:libexecdir]. Sorry for that!

thanks!

**Comment by Psukhe** [comment]
I think the attribute has changed in the later versions of apache cookbook.
https://github.com/tacitknowledge/aem-cookbook/pull/37 seems to resolve this issue, but won't work for earlier versions of the cookbook, which is probably why we hadn't gotten around to it yet.
We'll try and come up with a solution for both issues.
For now, you can set node[:apache][:libexecdir] to node[:apache][:libexec_dir] in your wrapper cookbook to resolve this issue.
After we merge in PR-37 this issue should be resolved.
Let me know if the work around doesn't work for you.
Thanks!

**Comment by wannesvc** [comment]
yup, working fine now, thanks!

**Pull request closed without merging**
